### ISSUE TITLE
Evaluate gitlab and github API clients gems - specifically dealing with issues

### ISSUE THREAD

**Issue by benichu** [benichu/checklister#24]
Evaluate options, give some usage examples, and utimately select one for each (or ideally a common one for both...)

**Comment by benichu** [comment]
https://github.com/NARKOZ/gitlab

**Comment by mdeloupy** [comment]
@benichu I'm gonna test https://github.com/NARKOZ/gitlab for Gitlab. It seems like the most used and complete gem. Gitlab's API documentation is [available here](https://github.com/gitlabhq/gitlabhq/tree/master/doc/api).

Github's API documentation [can be found here](https://developer.github.com/v3/). I'll test the following gems : 
- https://github.com/peter-murach/github
- https://github.com/octokit/octokit.rb - See [how to create an issue with Octokit](https://octokit.github.io/octokit.rb/Octokit/Client/Issues.html#create_issue-instance_method)

**Comment by benichu** [comment]
+1

**Comment by benichu** [comment]
using octokit for github
