### ISSUE TITLE
Improve setup explanation, especially where to find the private tokens for gitlab, mini "screenscast"?

### ISSUE THREAD

**Issue by benichu** [benichu/checklister#33]

**Comment by mdeloupy** [comment]
See : https://www.dropbox.com/s/e12pmlk5416hlac/Gitlab%20token.mp4?dl=0, and gif version to integrate to README : https://www.dropbox.com/s/1tpczblaxdmot9h/Gitlab%20token.gif?dl=0

**Comment by benichu** [comment]
looks good. the gif version seems very pixelated though.
we need 3 versions: github, new gitlab (gitlab.com) and "old" gitlab (intello's)

**Comment by benichu** [comment]
@mdeloupy we can see part of the recorder button in the frame's bottom left :(

**Comment by mdeloupy** [comment]
Updated videos : 
- Last Gitlab version : https://www.dropbox.com/s/e12pmlk5416hlac/Gitlab%20token.mp4?dl=0
- Old Gitlab version : https://www.dropbox.com/s/urkcdr9o3hvr2e9/Old%20Gitlab%20token.mp4?dl=0
- Github : https://www.dropbox.com/s/smnc1qdklwadvzu/Github%20token.mp4?dl=0

**Comment by benichu** [comment]
:+1:
