### ISSUE TITLE
Nasty error message when project is not found

### ISSUE THREAD

**Issue by raphschmidt** [benichu/checklister#50]
When running `checklister new --checklist some_valid_md_file.md`, I get prompted for a project name. If I enter something that doesn't match any projects, I get the following output:

```
error: undefined method `[]' for nil:NilClass
```

It would be nice if `checklister` could tell us nicely it didn't find any projects matching the entered string.

**Comment by benichu** [comment]
What is your checklister version? because I though I fixed that this morning for v1.0.0

**Comment by benichu** [comment]
Yes it's a bug. Will fix this for the next release v1.0.1

**Comment by benichu** [comment]
@mdeloupy can you take care of this?

**Comment by raphschmidt** [comment]
I'm running version 1.0.0.
