### ISSUE TITLE
can checklister support only being provided a .p12 file (without a CA crt)

### ISSUE THREAD

**Issue by 5ubstance** [benichu/checklister#60]
...that includes both the user's private crt and a ca's public crt?

**Comment by raphschmidt** [comment]
It looks like httparty only supports CA certs in .crt format.

I have a p12 file with embedded CA certificates. I tried setting it as the source for both my private cert and the CA cert, and got a `certificate verify failed` error when trying to create a new checklist.

Specifying the CA's crt file separately works fine. Unless httparty is updated to support embedded CA certs, I think we'll have to keep them in a separate crt file.

**Comment by benichu** [comment]
Thanks @raphschmidt, I'll make the CA certificate path compulsory during setup then....

**Comment by benichu** [comment]
I had already made it compulsory 😉 
https://github.com/benichu/checklister/blob/v1.1.0/bin/checklister#L117-L119
